#
#--------------------------------------------------------------------------
# python 3.11 alpine
#--------------------------------------------------------------------------
#

ARG PYTHON_VERSION=3.11.13
FROM python:${PYTHON_VERSION}-alpine
LABEL maintainer="chinayin <whereismoney@qq.com>"
ENV DEBIAN_FRONTEND=noninteractive

COPY prebuildfs /
