#
#--------------------------------------------------------------------------
# python 3.12 alpine
#--------------------------------------------------------------------------
#

ARG PYTHON_VERSION=3.12.11
FROM python:${PYTHON_VERSION}-alpine
LABEL maintainer="chinayin <whereismoney@qq.com>"
ENV DEBIAN_FRONTEND=noninteractive

COPY prebuildfs /
