#
#--------------------------------------------------------------------------
# python 3.11 debian
#--------------------------------------------------------------------------
#

ARG PYTHON_VERSION=3.11.12
FROM python:${PYTHON_VERSION}-slim
LABEL maintainer="chinayin <whereismoney@qq.com>"
ENV DEBIAN_FRONTEND=noninteractive

COPY prebuildfs /
