#
#--------------------------------------------------------------------------
# python 3.12 debian
#--------------------------------------------------------------------------
#

ARG PYTHON_VERSION=3.12.10
FROM python:${PYTHON_VERSION}-slim
LABEL maintainer="chinayin <whereismoney@qq.com>"
ENV DEBIAN_FRONTEND=noninteractive

COPY prebuildfs /
