name: Docker Image CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 4 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        major: [ 3.11, 3.12 ]
        os: [ debian, alpine ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.os }}
        run: |
          echo "repository=${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_OUTPUT
          echo "version=$(grep -oE 'PYTHON_VERSION=[0-9].[0-9]+.[0-9]+' Dockerfile | grep -oE '[0-9].[0-9]+.[0-9]+')" >> $GITHUB_OUTPUT
          echo "workdir=${{ matrix.major }}/${{ matrix.os }}" >> $GITHUB_OUTPUT
      - name: Set Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.vars.outputs.repository }}
          tags: |
            type=raw,value=${{ matrix.major }}-${{ matrix.os }}
            type=raw,value=${{ steps.vars.outputs.version }}-${{ matrix.os }}
            ${{ (matrix.os == 'debian' && format('type=raw,value={0}', matrix.major)) || '' }}
            ${{ (matrix.os == 'debian' && format('type=raw,value={0}', steps.vars.outputs.version)) || '' }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Copy files
        run: |
          cp -rf files/* ${{ matrix.major }}/${{ matrix.os }}/
          tree .
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
